import type { Equation } from "./equations";
import type { GraphViewport } from "./graph";
import { getGraphPaths } from "./equations";

export interface ExportOptions {
  width?: number;
  height?: number;
  theme?: "dark" | "light";
  includeGrid?: boolean;
  title?: string;
}

export function exportToSvg(
  equations: Equation[],
  viewport: GraphViewport,
  options: ExportOptions = {},
): string {
  const width = options.width ?? 800;
  const height = options.height ?? 500;
  const theme = options.theme ?? "dark";
  const bg = theme === "dark" ? "#0f172a" : "#ffffff";
  const axisColor = theme === "dark" ? "#475569" : "#cbd5e1";
  const gridColor = theme === "dark" ? "#1e293b" : "#f1f5f9";
  const textColor = theme === "dark" ? "#94a3b8" : "#64748b";

  const paths = getGraphPaths(equations);

  const mapX = (x: number) =>
    ((x - (viewport.centerX - viewport.spanX / 2)) / viewport.spanX) * width;
  const mapY = (y: number) =>
    height - ((y - (viewport.centerY - viewport.spanY / 2)) / viewport.spanY) * height;

  const originX = mapX(0);
  const originY = mapY(0);

  let gridLines = "";
  if (options.includeGrid ?? true) {
    const step = Math.pow(10, Math.floor(Math.log10(viewport.spanX))) / 2 || 1;
    const startX = Math.floor((viewport.centerX - viewport.spanX / 2) / step) * step;
    const endX = Math.ceil((viewport.centerX + viewport.spanX / 2) / step) * step;

    for (let x = startX; x <= endX; x += step) {
      const px = mapX(x);
      gridLines += `<line x1="${px}" y1="0" x2="${px}" y2="${height}" stroke="${gridColor}" stroke-width="1" />`;
    }

    const startY = Math.floor((viewport.centerY - viewport.spanY / 2) / step) * step;
    const endY = Math.ceil((viewport.centerY + viewport.spanY / 2) / step) * step;

    for (let y = startY; y <= endY; y += step) {
      const py = mapY(y);
      gridLines += `<line x1="0" y1="${py}" x2="${width}" y2="${py}" stroke="${gridColor}" stroke-width="1" />`;
    }
  }

  const axes = `
    <line x1="0" y1="${originY}" x2="${width}" y2="${originY}" stroke="${axisColor}" stroke-width="1.5" />
    <line x1="${originX}" y1="0" x2="${originX}" y2="${height}" stroke="${axisColor}" stroke-width="1.5" />
  `;

  const curveSvg = paths
    .map(({ color, trace }) => {
      if (trace.points.length < 2) return "";
      const d = trace.points
        .map((p, i) => `${i === 0 ? "M" : "L"} ${mapX(p.x).toFixed(2)} ${mapY(p.y).toFixed(2)}`)
        .join(" ");
      return `<path d="${d}" fill="none" stroke="${color}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" />`;
    })
    .join("\n");

  const legend = equations
    .filter((eq) => eq.visible)
    .map((eq, i) => {
      const ly = 30 + i * 24;
      return `
        <g transform="translate(20, ${ly})">
          <line x1="0" y1="0" x2="20" y2="0" stroke="${eq.color}" stroke-width="3" />
          <text x="30" y="4" fill="${textColor}" font-family="system-ui, sans-serif" font-size="12">${eq.canonicalExpression}</text>
        </g>
      `;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <rect width="${width}" height="${height}" fill="${bg}" />
  <g id="grid">${gridLines}</g>
  <g id="axes">${axes}</g>
  <g id="curves">${curveSvg}</g>
  <g id="legend">${legend}</g>
</svg>`;
}

export function exportToLatexBundle(equations: Equation[]): string {
  const visible = equations.filter((eq) => eq.visible);
  if (!visible.length) return "% No visible equations";

  const lines = [
    "% Generated by Sign2Graph",
    "\\begin{aligned}",
    ...visible.map((eq) => `  ${eq.latex || eq.canonicalExpression} \\\\`),
    "\\end{aligned}",
  ];
  return lines.join("\n");
}

export function exportToDataJson(equations: Equation[], viewport: GraphViewport): string {
  return JSON.stringify(
    {
      app: "Sign2Graph",
      version: "1.0",
      timestamp: new Date().toISOString(),
      viewport,
      equations: equations.map((eq) => ({
        id: eq.id,
        latex: eq.latex,
        canonicalExpression: eq.canonicalExpression,
        color: eq.color,
        visible: eq.visible,
      })),
    },
    null,
    2,
  );
}

export function downloadBlob(content: string, filename: string, mimeType: string) {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof navigator === "undefined" || !navigator.clipboard) {
    return false;
  }
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
